# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrain.proto\";\n\x07Triplet\x12\r\n\x05\x61rray\x18\x01 \x03(\x05\x12\x12\n\ndictionary\x18\x02 \x03(\x02\x12\r\n\x05value\x18\x03 \x01(\x01\"*\n\x0cTripletArray\x12\x1a\n\x08triplets\x18\x01 \x03(\x0b\x32\x08.Tripletb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'train_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRIPLET._serialized_start=15
  _TRIPLET._serialized_end=74
  _TRIPLETARRAY._serialized_start=76
  _TRIPLETARRAY._serialized_end=118
# @@protoc_insertion_point(module_scope)
