"""empty message

Revision ID: 1ae3141021bb
Revises: 1bb13b5e214a
Create Date: 2024-06-22 13:48:47.292141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae3141021bb'
down_revision = '1bb13b5e214a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('lose', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sgf',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('host', sa.Integer(), nullable=False),
    sa.Column('challenger', sa.Integer(), nullable=False),
    sa.Column('sgf', sa.String(length=500), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenger'], ['user.id'], ),
    sa.ForeignKeyConstraint(['host'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgf')
    op.drop_table('result')
    # ### end Alembic commands ###
