"""empty message

Revision ID: 1bb13b5e214a
Revises: 61671b6cc468
Create Date: 2024-06-05 00:15:53.800927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bb13b5e214a'
down_revision = '61671b6cc468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
