"""jingdong server

Revision ID: 718d769128f2
Revises: 
Create Date: 2024-09-20 23:41:51.572229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718d769128f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('lose', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sgf',
    sa.Column('id', sa.Integer(), nullable=False, auto_increment=True),
    sa.Column('host', sa.Integer(), nullable=False),
    sa.Column('challenger', sa.Integer(), nullable=False),
    sa.Column('sgf', sa.String(length=500), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenger'], ['user.id'], ),
    sa.ForeignKeyConstraint(['host'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgf')
    op.drop_table('result')
    op.drop_table('user')
    # ### end Alembic commands ###
